### ISSUE TITLE
merging does not resolve $ref

### ISSUE THREAD

**Issue by DavidBiesack** [robertmassaioli/openapi-merge#48] opened 2022-02-10 18:49 UTC
Perhaps this is beyond the scope of this tool, but I'd like it to resolve $`ref` correctly when merging.

When merging two openapi files where `a.yaml` references resources in `b.yaml`, for example:

`a.yaml` contains
```yaml
components:
  responses:
    '304':
      $ref: "b.yaml#/components/responses/304"
    '400':
      $ref: "b.yaml#/components/responses/400"
```

and `b.yaml` defines those responses:

```yaml
components:
  responses:
    '304':
      description: >-
        Not Modified. The resource has not been modified since it was last fetched.
    '400':
      description: >-
        Bad Request.
        The request body or one or more of the query parameters was not well formed.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/problemResponse'
    ...
```

when merging, the output file does not resolve and merge the references. The output file repeats the references
and then adds a suffix where there is duplication:

```yaml
components:
  responses:
    '304':
      $ref: b.yaml#/components/responses/304
    '400':
      $ref: b.yaml#/components/responses/400
    '3041':
      description: >-
        Not Modified. The resource has not been modified since it was last fetched.
    '4001':
      description: >-
        Bad Request. The request body or one or more of the query parameters was not well formed. 
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/problemResponse'
```

and the resulting file does not standalone -- it still requires `b.yaml`

To properly resolve the `$ref` this should be

```yaml
components:
  responses:
    '304':
      $ref: #/components/responses/304`
    '400':
      $ref: #/components/responses/4001
```

This should work for all `$ref` in the OpenAPI files (in schemas, etc.).

**Comment by robertmassaioli** [comment] 2022-03-21 22:30
This is a duplicate of #10 

I'm going to mark this as closed. For the record, my current recommendation is to use a tool to bundle the $ref's into your input files and then run openapi-merge over them. In that way, this is a composable tool. If I ever implement this feature request, it will be done as part of openapi-merge-cli and NOT as part of openapi-merge and the CLI tool will essentially perform that pre-bundling step for you.

I very much want the library to have one, and only one, job. This helps to make it more composable / reusable.

**Closed by robertmassaioli** 2022-03-21 22:30 UTC

**Comment by eropple** [comment] 2022-06-06 16:58
Saw this while I was attempting to wrap my head around openapi-merge. @robertmassaioli, if I'm reading the code correctly (and I might not be, to be clear), I'm not sure the openapi-merge logic will de-duplicate references that are bundled in from separate files?

If that's correct, it seems like bundling might reasonably be in scope. If not, obviously, ignore me. :D
